### PR TITLE
Finally u can change conds font and esp font

### PR DESCRIPTION
**Pull request by D1am0nds-Ore**
x

### CODE REVIEW

**Comment by phonkv2** [comment]
Those who know

**Comment by D1am0nds-Ore** [comment]
duh i miss click
i just wanna merge test branch to main

**Comment by phonkv2** [comment]
???

**Comment by Gergish001** [comment]
bad shit ig, just pasted fusion

**Comment by D1am0nds-Ore** [comment]
dud
i miss clicked. i just wanna merge beta to my main branch. duh

**Pull request closed without merging**
